// THIS FILE HAS BEEN AUTO-GENERATED BY THE 'DEAR BINDINGS' GENERATOR.
// **DO NOT EDIT DIRECTLY**
// https://github.com/dearimgui/dear_bindings

#include "imgui.h"
#include "imgui_impl_dx12.h"

#include <stdio.h>
#include <d3d12.h>

// Wrap this in a namespace to keep it separate from the C++ API
namespace cimgui
{
#include "cimgui_impl_dx12.h"
}

// By-value struct conversions

// Function stubs

#ifndef IMGUI_DISABLE

CIMGUI_IMPL_API bool cimgui::cImGui_ImplDX12_Init(cimgui::ID3D12Device* device, int num_frames_in_flight, DXGI_FORMAT rtv_format, cimgui::ID3D12DescriptorHeap* cbv_srv_heap, cimgui::D3D12_CPU_DESCRIPTOR_HANDLE font_srv_cpu_desc_handle, cimgui::D3D12_GPU_DESCRIPTOR_HANDLE font_srv_gpu_desc_handle)
{
    return ::ImGui_ImplDX12_Init(reinterpret_cast<::ID3D12Device*>(device), num_frames_in_flight, rtv_format, reinterpret_cast<::ID3D12DescriptorHeap*>(cbv_srv_heap), (*reinterpret_cast<::D3D12_CPU_DESCRIPTOR_HANDLE*>(&font_srv_cpu_desc_handle)), (*reinterpret_cast<::D3D12_GPU_DESCRIPTOR_HANDLE*>(&font_srv_gpu_desc_handle)));
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplDX12_Shutdown(void)
{
    ::ImGui_ImplDX12_Shutdown();
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplDX12_NewFrame(void)
{
    ::ImGui_ImplDX12_NewFrame();
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplDX12_RenderDrawData(cimgui::ImDrawData* draw_data, cimgui::ID3D12GraphicsCommandList* graphics_command_list)
{
    ::ImGui_ImplDX12_RenderDrawData(reinterpret_cast<::ImDrawData*>(draw_data), reinterpret_cast<::ID3D12GraphicsCommandList*>(graphics_command_list));
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplDX12_InvalidateDeviceObjects(void)
{
    ::ImGui_ImplDX12_InvalidateDeviceObjects();
}

CIMGUI_IMPL_API bool cimgui::cImGui_ImplDX12_CreateDeviceObjects(void)
{
    return ::ImGui_ImplDX12_CreateDeviceObjects();
}

#endif // #ifndef IMGUI_DISABLE
