// THIS FILE HAS BEEN AUTO-GENERATED BY THE 'DEAR BINDINGS' GENERATOR.
// **DO NOT EDIT DIRECTLY**
// https://github.com/dearimgui/dear_bindings

#include "imgui.h"
#include "imgui_impl_dx11.h"

#include <stdio.h>

// Wrap this in a namespace to keep it separate from the C++ API
namespace cimgui
{
#include "cimgui_impl_dx11.h"
}

// By-value struct conversions

// Function stubs

#ifndef IMGUI_DISABLE

CIMGUI_IMPL_API bool cimgui::cImGui_ImplDX11_Init(cimgui::ID3D11Device* device, cimgui::ID3D11DeviceContext* device_context)
{
    return ::ImGui_ImplDX11_Init(reinterpret_cast<::ID3D11Device*>(device), reinterpret_cast<::ID3D11DeviceContext*>(device_context));
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplDX11_Shutdown(void)
{
    ::ImGui_ImplDX11_Shutdown();
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplDX11_NewFrame(void)
{
    ::ImGui_ImplDX11_NewFrame();
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplDX11_RenderDrawData(cimgui::ImDrawData* draw_data)
{
    ::ImGui_ImplDX11_RenderDrawData(reinterpret_cast<::ImDrawData*>(draw_data));
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplDX11_InvalidateDeviceObjects(void)
{
    ::ImGui_ImplDX11_InvalidateDeviceObjects();
}

CIMGUI_IMPL_API bool cimgui::cImGui_ImplDX11_CreateDeviceObjects(void)
{
    return ::ImGui_ImplDX11_CreateDeviceObjects();
}

#endif // #ifndef IMGUI_DISABLE
