// THIS FILE HAS BEEN AUTO-GENERATED BY THE 'DEAR BINDINGS' GENERATOR.
// **DO NOT EDIT DIRECTLY**
// https://github.com/dearimgui/dear_bindings

#include "imgui.h"
#include "imgui_impl_android.h"

#include <stdio.h>

// Wrap this in a namespace to keep it separate from the C++ API
namespace cimgui
{
#include "cimgui_impl_android.h"
}

// By-value struct conversions

// Function stubs

#ifndef IMGUI_DISABLE

CIMGUI_IMPL_API bool cimgui::cImGui_ImplAndroid_Init(cimgui::ANativeWindow* window)
{
    return ::ImGui_ImplAndroid_Init(reinterpret_cast<::ANativeWindow*>(window));
}

CIMGUI_IMPL_API int32_t cimgui::cImGui_ImplAndroid_HandleInputEvent(const cimgui::AInputEvent* input_event)
{
    return ::ImGui_ImplAndroid_HandleInputEvent(reinterpret_cast<const ::AInputEvent*>(input_event));
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplAndroid_Shutdown(void)
{
    ::ImGui_ImplAndroid_Shutdown();
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplAndroid_NewFrame(void)
{
    ::ImGui_ImplAndroid_NewFrame();
}

#endif // #ifndef IMGUI_DISABLE
