// THIS FILE HAS BEEN AUTO-GENERATED BY THE 'DEAR BINDINGS' GENERATOR.
// **DO NOT EDIT DIRECTLY**
// https://github.com/dearimgui/dear_bindings

#include "imgui.h"
#include "imgui_impl_wgpu.h"

#include <stdio.h>

// Wrap this in a namespace to keep it separate from the C++ API
namespace cimgui
{
#include "cimgui_impl_wgpu.h"
}

// By-value struct conversions

// Function stubs

#ifndef IMGUI_DISABLE

CIMGUI_IMPL_API bool cimgui::cImGui_ImplWGPU_Init(cimgui::ImGui_ImplWGPU_InitInfo* init_info)
{
    return ::ImGui_ImplWGPU_Init(reinterpret_cast<::ImGui_ImplWGPU_InitInfo*>(init_info));
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplWGPU_Shutdown(void)
{
    ::ImGui_ImplWGPU_Shutdown();
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplWGPU_NewFrame(void)
{
    ::ImGui_ImplWGPU_NewFrame();
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplWGPU_RenderDrawData(ImDrawData* draw_data, WGPURenderPassEncoder pass_encoder)
{
    ::ImGui_ImplWGPU_RenderDrawData(draw_data, pass_encoder);
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplWGPU_InvalidateDeviceObjects(void)
{
    ::ImGui_ImplWGPU_InvalidateDeviceObjects();
}

CIMGUI_IMPL_API bool cimgui::cImGui_ImplWGPU_CreateDeviceObjects(void)
{
    return ::ImGui_ImplWGPU_CreateDeviceObjects();
}

#endif // #ifndef IMGUI_DISABLE
