// THIS FILE HAS BEEN AUTO-GENERATED BY THE 'DEAR BINDINGS' GENERATOR.
// **DO NOT EDIT DIRECTLY**
// https://github.com/dearimgui/dear_bindings

#include "imgui.h"
#include "imgui_impl_glut.h"

#include <stdio.h>

// Wrap this in a namespace to keep it separate from the C++ API
namespace cimgui
{
#include "cimgui_impl_glut.h"
}

// By-value struct conversions

// Function stubs

#ifndef IMGUI_DISABLE

CIMGUI_IMPL_API bool cimgui::cImGui_ImplGLUT_Init(void)
{
    return ::ImGui_ImplGLUT_Init();
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplGLUT_InstallFuncs(void)
{
    ::ImGui_ImplGLUT_InstallFuncs();
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplGLUT_Shutdown(void)
{
    ::ImGui_ImplGLUT_Shutdown();
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplGLUT_NewFrame(void)
{
    ::ImGui_ImplGLUT_NewFrame();
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplGLUT_ReshapeFunc(int w, int h)
{
    ::ImGui_ImplGLUT_ReshapeFunc(w, h);
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplGLUT_MotionFunc(int x, int y)
{
    ::ImGui_ImplGLUT_MotionFunc(x, y);
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplGLUT_MouseFunc(int button, int state, int x, int y)
{
    ::ImGui_ImplGLUT_MouseFunc(button, state, x, y);
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplGLUT_MouseWheelFunc(int button, int dir, int x, int y)
{
    ::ImGui_ImplGLUT_MouseWheelFunc(button, dir, x, y);
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplGLUT_KeyboardFunc(unsigned char c, int x, int y)
{
    ::ImGui_ImplGLUT_KeyboardFunc(c, x, y);
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplGLUT_KeyboardUpFunc(unsigned char c, int x, int y)
{
    ::ImGui_ImplGLUT_KeyboardUpFunc(c, x, y);
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplGLUT_SpecialFunc(int key, int x, int y)
{
    ::ImGui_ImplGLUT_SpecialFunc(key, x, y);
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplGLUT_SpecialUpFunc(int key, int x, int y)
{
    ::ImGui_ImplGLUT_SpecialUpFunc(key, x, y);
}

#endif // #ifndef IMGUI_DISABLE
