// THIS FILE HAS BEEN AUTO-GENERATED BY THE 'DEAR BINDINGS' GENERATOR.
// **DO NOT EDIT DIRECTLY**
// https://github.com/dearimgui/dear_bindings

#include "imgui.h"
#include "imgui_impl_opengl2.h"

#include <stdio.h>

// Wrap this in a namespace to keep it separate from the C++ API
namespace cimgui
{
#include "cimgui_impl_opengl2.h"
}

// By-value struct conversions

// Function stubs

#ifndef IMGUI_DISABLE

CIMGUI_IMPL_API bool cimgui::cImGui_ImplOpenGL2_Init(void)
{
    return ::ImGui_ImplOpenGL2_Init();
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplOpenGL2_Shutdown(void)
{
    ::ImGui_ImplOpenGL2_Shutdown();
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplOpenGL2_NewFrame(void)
{
    ::ImGui_ImplOpenGL2_NewFrame();
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplOpenGL2_RenderDrawData(cimgui::ImDrawData* draw_data)
{
    ::ImGui_ImplOpenGL2_RenderDrawData(reinterpret_cast<::ImDrawData*>(draw_data));
}

CIMGUI_IMPL_API bool cimgui::cImGui_ImplOpenGL2_CreateFontsTexture(void)
{
    return ::ImGui_ImplOpenGL2_CreateFontsTexture();
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplOpenGL2_DestroyFontsTexture(void)
{
    ::ImGui_ImplOpenGL2_DestroyFontsTexture();
}

CIMGUI_IMPL_API bool cimgui::cImGui_ImplOpenGL2_CreateDeviceObjects(void)
{
    return ::ImGui_ImplOpenGL2_CreateDeviceObjects();
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplOpenGL2_DestroyDeviceObjects(void)
{
    ::ImGui_ImplOpenGL2_DestroyDeviceObjects();
}

#endif // #ifndef IMGUI_DISABLE
