// THIS FILE HAS BEEN AUTO-GENERATED BY THE 'DEAR BINDINGS' GENERATOR.
// **DO NOT EDIT DIRECTLY**
// https://github.com/dearimgui/dear_bindings

#include "imgui.h"
#include "imgui_impl_win32.h"

#include <stdio.h>

#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <windows.h>

// This define indicates that we have windows.h included
#define IMGUI_BACKEND_HAS_WINDOWS_H

// We need to manually declare this
extern IMGUI_IMPL_API LRESULT ImGui_ImplWin32_WndProcHandler(HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam);

// Wrap this in a namespace to keep it separate from the C++ API
namespace cimgui
{
#include "cimgui_impl_win32.h"
}

// By-value struct conversions

// Function stubs

#ifndef IMGUI_DISABLE

CIMGUI_IMPL_API bool cimgui::cImGui_ImplWin32_Init(void* hwnd)
{
    return ::ImGui_ImplWin32_Init(hwnd);
}

CIMGUI_IMPL_API bool cimgui::cImGui_ImplWin32_InitForOpenGL(void* hwnd)
{
    return ::ImGui_ImplWin32_InitForOpenGL(hwnd);
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplWin32_Shutdown(void)
{
    ::ImGui_ImplWin32_Shutdown();
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplWin32_NewFrame(void)
{
    ::ImGui_ImplWin32_NewFrame();
}

#ifdef IMGUI_BACKEND_HAS_WINDOWS_H

CIMGUI_IMPL_API LRESULT cimgui::cImGui_ImplWin32_WndProcHandler(HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam)
{
    return ::ImGui_ImplWin32_WndProcHandler(hWnd, msg, wParam, lParam);
}

#endif // #ifdef IMGUI_BACKEND_HAS_WINDOWS_H

CIMGUI_IMPL_API void cimgui::cImGui_ImplWin32_EnableDpiAwareness(void)
{
    ::ImGui_ImplWin32_EnableDpiAwareness();
}

CIMGUI_IMPL_API float cimgui::cImGui_ImplWin32_GetDpiScaleForHwnd(void* hwnd)
{
    return ::ImGui_ImplWin32_GetDpiScaleForHwnd(hwnd);
}

CIMGUI_IMPL_API float cimgui::cImGui_ImplWin32_GetDpiScaleForMonitor(void* monitor)
{
    return ::ImGui_ImplWin32_GetDpiScaleForMonitor(monitor);
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplWin32_EnableAlphaCompositing(void* hwnd)
{
    ::ImGui_ImplWin32_EnableAlphaCompositing(hwnd);
}

#endif // #ifndef IMGUI_DISABLE
