// THIS FILE HAS BEEN AUTO-GENERATED BY THE 'DEAR BINDINGS' GENERATOR.
// **DO NOT EDIT DIRECTLY**
// https://github.com/dearimgui/dear_bindings

#include "imgui.h"
#include "imgui_impl_opengl3.h"

#include <stdio.h>

// Wrap this in a namespace to keep it separate from the C++ API
namespace cimgui
{
#include "dcimgui_impl_opengl3.h"
}

// By-value struct conversions

static inline cimgui::ImVec2 ConvertFromCPP_ImVec2(const ::ImVec2& src)
{
    cimgui::ImVec2 dest;
    dest.x = src.x;
    dest.y = src.y;
    return dest;
}

static inline ::ImVec2 ConvertToCPP_ImVec2(const cimgui::ImVec2& src)
{
    ::ImVec2 dest;
    dest.x = src.x;
    dest.y = src.y;
    return dest;
}

static inline cimgui::ImVec4 ConvertFromCPP_ImVec4(const ::ImVec4& src)
{
    cimgui::ImVec4 dest;
    dest.x = src.x;
    dest.y = src.y;
    dest.z = src.z;
    dest.w = src.w;
    return dest;
}

static inline ::ImVec4 ConvertToCPP_ImVec4(const cimgui::ImVec4& src)
{
    ::ImVec4 dest;
    dest.x = src.x;
    dest.y = src.y;
    dest.z = src.z;
    dest.w = src.w;
    return dest;
}

static inline cimgui::ImColor ConvertFromCPP_ImColor(const ::ImColor& src)
{
    cimgui::ImColor dest;
    dest.Value.x = src.Value.x;
    dest.Value.y = src.Value.y;
    dest.Value.z = src.Value.z;
    dest.Value.w = src.Value.w;
    return dest;
}

static inline ::ImColor ConvertToCPP_ImColor(const cimgui::ImColor& src)
{
    ::ImColor dest;
    dest.Value.x = src.Value.x;
    dest.Value.y = src.Value.y;
    dest.Value.z = src.Value.z;
    dest.Value.w = src.Value.w;
    return dest;
}

// Function stubs

#ifndef IMGUI_DISABLE

CIMGUI_IMPL_API bool cimgui::cImGui_ImplOpenGL3_Init(void)
{
    return ::ImGui_ImplOpenGL3_Init();
}

CIMGUI_IMPL_API bool cimgui::cImGui_ImplOpenGL3_InitEx(const char* glsl_version)
{
    return ::ImGui_ImplOpenGL3_Init(glsl_version);
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplOpenGL3_Shutdown(void)
{
    ::ImGui_ImplOpenGL3_Shutdown();
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplOpenGL3_NewFrame(void)
{
    ::ImGui_ImplOpenGL3_NewFrame();
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplOpenGL3_RenderDrawData(cimgui::ImDrawData* draw_data)
{
    ::ImGui_ImplOpenGL3_RenderDrawData(reinterpret_cast<::ImDrawData*>(draw_data));
}

CIMGUI_IMPL_API bool cimgui::cImGui_ImplOpenGL3_CreateFontsTexture(void)
{
    return ::ImGui_ImplOpenGL3_CreateFontsTexture();
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplOpenGL3_DestroyFontsTexture(void)
{
    ::ImGui_ImplOpenGL3_DestroyFontsTexture();
}

CIMGUI_IMPL_API bool cimgui::cImGui_ImplOpenGL3_CreateDeviceObjects(void)
{
    return ::ImGui_ImplOpenGL3_CreateDeviceObjects();
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplOpenGL3_DestroyDeviceObjects(void)
{
    ::ImGui_ImplOpenGL3_DestroyDeviceObjects();
}

#endif // #ifndef IMGUI_DISABLE
