// THIS FILE HAS BEEN AUTO-GENERATED BY THE 'DEAR BINDINGS' GENERATOR.
// **DO NOT EDIT DIRECTLY**
// https://github.com/dearimgui/dear_bindings

#include "imgui.h"
#include "imgui_impl_dx10.h"

#include <stdio.h>

// Wrap this in a namespace to keep it separate from the C++ API
namespace cimgui
{
#include "cimgui_impl_dx10.h"
}

// By-value struct conversions

// Function stubs

#ifndef IMGUI_DISABLE

CIMGUI_IMPL_API bool cimgui::cImGui_ImplDX10_Init(cimgui::ID3D10Device* device)
{
    return ::ImGui_ImplDX10_Init(reinterpret_cast<::ID3D10Device*>(device));
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplDX10_Shutdown(void)
{
    ::ImGui_ImplDX10_Shutdown();
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplDX10_NewFrame(void)
{
    ::ImGui_ImplDX10_NewFrame();
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplDX10_RenderDrawData(cimgui::ImDrawData* draw_data)
{
    ::ImGui_ImplDX10_RenderDrawData(reinterpret_cast<::ImDrawData*>(draw_data));
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplDX10_InvalidateDeviceObjects(void)
{
    ::ImGui_ImplDX10_InvalidateDeviceObjects();
}

CIMGUI_IMPL_API bool cimgui::cImGui_ImplDX10_CreateDeviceObjects(void)
{
    return ::ImGui_ImplDX10_CreateDeviceObjects();
}

#endif // #ifndef IMGUI_DISABLE
