// THIS FILE HAS BEEN AUTO-GENERATED BY THE 'DEAR BINDINGS' GENERATOR.
// **DO NOT EDIT DIRECTLY**
// https://github.com/dearimgui/dear_bindings

#include "imgui.h"
#include "imgui_impl_null.h"

#include <stdio.h>

// Wrap this in a namespace to keep it separate from the C++ API
namespace cimgui
{
#include "dcimgui_impl_null.h"
}

// By-value struct conversions

static inline cimgui::ImVec2 ConvertFromCPP_ImVec2(const ::ImVec2& src)
{
    cimgui::ImVec2 dest;
    dest.x = src.x;
    dest.y = src.y;
    return dest;
}

static inline ::ImVec2 ConvertToCPP_ImVec2(const cimgui::ImVec2& src)
{
    ::ImVec2 dest;
    dest.x = src.x;
    dest.y = src.y;
    return dest;
}

static inline cimgui::ImVec4 ConvertFromCPP_ImVec4(const ::ImVec4& src)
{
    cimgui::ImVec4 dest;
    dest.x = src.x;
    dest.y = src.y;
    dest.z = src.z;
    dest.w = src.w;
    return dest;
}

static inline ::ImVec4 ConvertToCPP_ImVec4(const cimgui::ImVec4& src)
{
    ::ImVec4 dest;
    dest.x = src.x;
    dest.y = src.y;
    dest.z = src.z;
    dest.w = src.w;
    return dest;
}

static inline cimgui::ImTextureRef ConvertFromCPP_ImTextureRef(const ::ImTextureRef& src)
{
    cimgui::ImTextureRef dest;
    dest._TexData = reinterpret_cast<cimgui::ImTextureData*>(src._TexData);
    dest._TexID = src._TexID;
    return dest;
}

static inline ::ImTextureRef ConvertToCPP_ImTextureRef(const cimgui::ImTextureRef& src)
{
    ::ImTextureRef dest;
    dest._TexData = reinterpret_cast<::ImTextureData*>(src._TexData);
    dest._TexID = src._TexID;
    return dest;
}

static inline cimgui::ImColor ConvertFromCPP_ImColor(const ::ImColor& src)
{
    cimgui::ImColor dest;
    dest.Value.x = src.Value.x;
    dest.Value.y = src.Value.y;
    dest.Value.z = src.Value.z;
    dest.Value.w = src.Value.w;
    return dest;
}

static inline ::ImColor ConvertToCPP_ImColor(const cimgui::ImColor& src)
{
    ::ImColor dest;
    dest.Value.x = src.Value.x;
    dest.Value.y = src.Value.y;
    dest.Value.z = src.Value.z;
    dest.Value.w = src.Value.w;
    return dest;
}

// Function stubs

#ifndef IMGUI_DISABLE

CIMGUI_IMPL_API bool cimgui::cImGui_ImplNull_Init(void)
{
    return ::ImGui_ImplNull_Init();
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplNull_Shutdown(void)
{
    ::ImGui_ImplNull_Shutdown();
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplNull_NewFrame(void)
{
    ::ImGui_ImplNull_NewFrame();
}

CIMGUI_IMPL_API bool cimgui::cImGui_ImplNullPlatform_Init(void)
{
    return ::ImGui_ImplNullPlatform_Init();
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplNullPlatform_Shutdown(void)
{
    ::ImGui_ImplNullPlatform_Shutdown();
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplNullPlatform_NewFrame(void)
{
    ::ImGui_ImplNullPlatform_NewFrame();
}

CIMGUI_IMPL_API bool cimgui::cImGui_ImplNullRender_Init(void)
{
    return ::ImGui_ImplNullRender_Init();
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplNullRender_Shutdown(void)
{
    ::ImGui_ImplNullRender_Shutdown();
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplNullRender_NewFrame(void)
{
    ::ImGui_ImplNullRender_NewFrame();
}

CIMGUI_IMPL_API void cimgui::cImGui_ImplNullRender_RenderDrawData(cimgui::ImDrawData* draw_data)
{
    ::ImGui_ImplNullRender_RenderDrawData(reinterpret_cast<::ImDrawData*>(draw_data));
}

#endif // #ifndef IMGUI_DISABLE
