// THIS FILE HAS BEEN AUTO-GENERATED BY THE 'DEAR BINDINGS' GENERATOR.
// **DO NOT EDIT DIRECTLY**
// https://github.com/dearimgui/dear_bindings

// dear imgui: Null Platform+Renderer Backends
// ImDrawIdx: vertex index. [Compile-time configurable type]
// - To use 16-bit indices + allow large meshes: backend need to set 'io.BackendFlags |= ImGuiBackendFlags_RendererHasVtxOffset' and handle ImDrawCmd::VtxOffset (recommended).
// - To use 32-bit indices: override with '#define ImDrawIdx unsigned int' in your imconfig.h file.
#ifndef ImDrawIdx
typedef unsigned short ImDrawIdx;  // Default: 16-bit (for maximum compatibility with renderer backends)
#endif // #ifndef ImDrawIdx
// This is designed if you need to use a blind Dear Imgui context with no input and no output.

// You can use unmodified imgui_impl_* files in your project. See examples/ folder for examples of using this.
// Prefer including the entire imgui/ repository into your project (either as a copy or as a submodule), and only build the backends you need.
// Learn about Dear ImGui:
// - FAQ                  https://dearimgui.com/faq
// - Getting Started      https://dearimgui.com/getting-started
// - Documentation        https://dearimgui.com/docs (same as your local docs/ folder).
// - Introduction, links and more at the top of imgui.cpp

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif
#include "dcimgui.h"
#ifndef IMGUI_DISABLE
// Follow "Getting Started" link and check examples/ folder to learn about using backends!

typedef struct ImDrawData_t ImDrawData;
// Null = NullPlatform + NullRender
CIMGUI_IMPL_API bool cImGui_ImplNull_Init(void);
CIMGUI_IMPL_API void cImGui_ImplNull_Shutdown(void);
CIMGUI_IMPL_API void cImGui_ImplNull_NewFrame(void);

// Null platform only (single screen, fixed timestep, no inputs)
CIMGUI_IMPL_API bool cImGui_ImplNullPlatform_Init(void);
CIMGUI_IMPL_API void cImGui_ImplNullPlatform_Shutdown(void);
CIMGUI_IMPL_API void cImGui_ImplNullPlatform_NewFrame(void);

// Null renderer only (no output)
CIMGUI_IMPL_API bool cImGui_ImplNullRender_Init(void);
CIMGUI_IMPL_API void cImGui_ImplNullRender_Shutdown(void);
CIMGUI_IMPL_API void cImGui_ImplNullRender_NewFrame(void);
CIMGUI_IMPL_API void cImGui_ImplNullRender_RenderDrawData(ImDrawData* draw_data);
#endif// #ifndef IMGUI_DISABLE
#ifdef __cplusplus
} // End of extern "C" block
#endif
