name: ci

on:
  pull_request:
    branches:
      - trunk

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: mlugg/setup-zig@v2
    - name: Check zig is canonical
      shell: bash
      run: |
        zig fmt --check .
  examples:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    runs-on: "${{ matrix.os }}"
    steps:
    - uses: actions/checkout@v4
    - uses: mlugg/setup-zig@v2
    - name: Test building examples
      shell: bash
      run: |
        unset ZIG_LOCAL_CACHE_DIR
        zig build --build-file "${GITHUB_WORKSPACE}/examples/build.zig"
  build:
    strategy:
      matrix:
        repo:
          - spaceporn
        os:
          - ubuntu-latest
          - windows-latest
        zig_opts:
          - ''
          - '-Ddev'
          - '-Dturbo'
    runs-on: "${{ matrix.os }}"
    steps:
    - name: Setup Zig
      uses: mlugg/setup-zig@v2
    - uses: actions/checkout@v4
      with:
        repository: "${{ github.repository_owner }}/${{ matrix.repo }}"

    - name: Prepare ${{ matrix.repo }}/build.zig.zon
      env:
        URL: "git+${{ github.server_url }}/${{ github.repository }}#${{ github.event.pull_request.head.sha }}"
      shell: 'bash'
      run: |
        zig fetch --save "${URL}"

    - name: Test building ${{ matrix.repo }}
      env:
        OPTIONS: "${{ matrix.zig_opts }}"
        RUNNER_TMP: "${{ runner.temp }}"
      shell: bash
      run:
        zig build ${OPTIONS}
