name: ci

on:
  pull_request:
    branches:
      - trunk

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: mlugg/setup-zig@v2
    - name: Check zig is canonical
      shell: bash
      run: |
        zig fmt --check .
  examples:
    strategy:
      matrix:
        os:
          - ubuntu
          - windows
          - macos
    runs-on: "${{ matrix.os }}-latest"
    steps:
    - uses: actions/checkout@v4
    - uses: mlugg/setup-zig@v2
    - name: Test building examples
      shell: bash
      run: |
        unset ZIG_LOCAL_CACHE_DIR
        env -C "${GITHUB_WORKSPACE}/examples" zig build
        env -C "${GITHUB_WORKSPACE}/examples" zig build -Ddocking
  maintainance:
    runs-on: ubuntu-latest
    steps:
    - name: Install packages
      shell: 'bash'
      run: |
        sudo apt-get update --fix-missing
        sudo apt-get install -y python3-venv mesa-utils
        printf 'ACTIVATE_DIR=bin\n' >> "${GITHUB_ENV}"

    - uses: actions/checkout@v4
    - name: Setup Zig
      uses: mlugg/setup-zig@v2

    - name: Activate python virtual env & install pip packages
      env:
        RUNNER_TMP: "${{ runner.temp }}"
      shell: 'bash'
      run: |
        python3 -m venv "${RUNNER_TMP}/venv"
        source "${RUNNER_TMP}/venv/${ACTIVATE_DIR:-Scripts}/activate"
        pip install ply

    - name: Test updating
      env:
        RUNNER_TMP: "${{ runner.temp }}"
      shell: 'bash'
      run: |
        source "${RUNNER_TMP}/venv/${ACTIVATE_DIR:-Scripts}/activate"
        zig build -Dupdate -Dverbose

    - name: Test fetching
      env:
        RUNNER_TMP: "${{ runner.temp }}"
      shell: 'bash'
      run: |
        source "${RUNNER_TMP}/venv/${ACTIVATE_DIR:-Scripts}/activate"
        zig build -Dfetch -Dverbose
