name: ci

on:
  pull_request:
    branches:
      - trunk

jobs:
  build:
    strategy:
      matrix:
        repo:
          - spaceporn
    runs-on: ubuntu-latest
    steps:
    - uses: tiawl/spaceporn-dep-action-ci@v1.0.0
      with:
        repository: "${{ github.repository }}"
        sha: "${{ github.sha }}"
        user: "${{ matrix.repo }}"
        token: "${{ github.token }}"
        test_build: 'true'
        test_update: 'false'
        test_fetch: 'false'
