name: new-tag

on:
  workflow_dispatch:
    inputs:
      new-tag:
        description: 'New tag'
        required: true

jobs:
  new-tag:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v6
      with:
        repository: "${{ github.repository }}"

    - name: Setup git user information, create and push new tag
      env:
        NAME: "GitHub Actions[bot]"
        EMAIL: "<>"
        BRANCH: "${{ github.event.repository.default_branch }}"
        NEW_TAG: "${{ github.event.inputs.new-tag }}"
        GH_TOKEN: "${{ github.token }}"
      shell: 'bash'
      run: |
        set -x
        git config user.name "${NAME}"
        git config user.email "${EMAIL}"
        git checkout "${BRANCH}"
        git tag "${NEW_TAG}"
        git push --tags
