name: cd pong

on:
  repository_dispatch:
    types:
      - ping-from-toolbox
      - ping-from-glfw.zig
      - ping-from-spaceporn-action-bot
      - ping-from-spaceporn-action-ci
      - ping-from-spaceporn-action-cd-ping
      - ping-from-spaceporn-action-cd-pong

jobs:
  pong:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: tiawl/spaceporn-action-cd-pong@v1.0.1
      with:
        to: "${{ github.repository }}"
        from: "${{ github.event.client_payload.from }}"
        tag: "${{ github.event.client_payload.tag }}"
        hash: "${{ github.event.client_payload.hash }}"
        token: "${{ secrets.PAT }}"
