name: cd pong

on:
  repository_dispatch:
    types:
      - ping

jobs:
  pong:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: tiawl/spaceporn-dep-action-cd-pong@v1
      if: contains(fromJSON('["toolbox","glfw.zig"]'), github.event.client_payload.dependency)
      with:
        dependency: "${{ github.event.client_payload.dependency }}"
        tag: "${{ github.event.client_payload.tag }}"
        hash: "${{ github.event.client_payload.hash }}"
        token: "${{ github.token }}"
