name: cd pong

on:
  repository_dispatch:
    types:
      - ping-toolbox
      - ping-glfw.zig
      - ping-spaceporn-action-bot
      - ping-spaceporn-action-ci
      - ping-spaceporn-action-cd-ping
      - ping-spaceporn-action-cd-pong

jobs:
  pong:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: tiawl/spaceporn-action-cd-pong@v1.0.0
      with:
        repository: "${{ github.repository }}"
        dependency: "${{ github.event.client_payload.dependency }}"
        tag: "${{ github.event.client_payload.tag }}"
        hash: "${{ github.event.client_payload.hash }}"
        token: "${{ secrets.PAT }}"
